### ISSUE TITLE
Implement program areas

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#1]
Each project should be associated to at least one program area. Program areas need to be able to have their own outputs and outcomes, which should be aggregated from related projects. The aggregation definition needs to be manually specified:

Program 1 has the output "Trainig sessions completed"
Project 1 has the output "Successful teacher training sessions"
Project 2 has the output "User education opportunities provided"

The program administrator should be able to link the outputs from project 1 and 2 to the output in program 1. Similar model for outcomes.

**Comment by booski** [comment]
Exact implementation of this feature will require further discussion with spider program managers.

**Comment by booski** [comment]
An initial implementation of program areas can skip the aggregation handling and only enable creation of program areas and connection of a project to one or more program areas.

**Comment by booski** [comment]
Project areas are needed asap. As above, let's stick with the basic implementation first and wait with aggregation handling, so these functions are needed first:

 - Create program areas
 - Connect a project to an area (can be several, should not be mandatory yet)
 - Add ability to filter by program area to the project list page
 - Add a program area page that lists the projects in that area. Will in future be expanded to do output aggregation etc.

**Comment by orkit** [comment]
Program Areas are now implemented. A project can connect to one or several program areas (not mandatory). Spider/administrator users have a filter in the project list page.
Program area names and descriptions can be edited. Each program area have their own outputs and outcomes (for now hidden)
