### ISSUE TITLE
Draft updates

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#11]
Project updates should have the ability to be saved as a draft before being properly submitted. Draft updates should not have their modifications logged (until proper submission).

**Comment by pavelsokolov** [comment]
Draft updates are ready. Now they're needed to be excluded from logging.

**Comment by pavelsokolov** [comment]
@orkit I assume with the latest commit this can be considered as done?

**Comment by orkit** [comment]
@pavelsokolov you wanted to "hide" outputs created during a submitted draft.
