### ISSUE TITLE
Implement user authentication for project partners

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#14]
Project partners won't be able to login using (normal) SSO. Alternative options include OAuth and local accounts.

**Comment by orkit** [comment]
I suggest that we use a local account login with an invitation system. A spider coworker can then send invitations to specific people (partners) who can log in to the system after the invitation. In addition, it should be discussed what a partner may do in the system.

**Comment by booski** [comment]
After discussing it with spider, they would like both local logins and the option to use google, facebook and linkedin. As far as i know they all implement OAuth2/OpenID, so given support for OpenID it should just be a matter of adding buttons to the login page for all supported services.

@orkit's suggestion of invites is a good one, all partner accounts should require an invite in order to be able to sign up, no matter the login method.

**Comment by orkit** [comment]
Local accounts are now implemented. A spider who is the manager of a project can now invite partners to the project. The partner will receive an email notification and asked to click a button (or a link) to redirect to a registration page. After registration, the user will be connected to the project they have been invited to and be authorized to write an update for that project only.
TODO: forgotten password reset function and  implement login via google / facebook / linkedin

**Comment by orkit** [comment]
Oauth2 Login implementation via Github/Facebook/Linkedin and Google has been setup. The Credentials can be set in the /systemconfig/resultpress.ini file.
