### ISSUE TITLE
Implement user authentication for spider users

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#2]
Spider users should log in with shibboleth (preferrably without needing to be prompted as usual).

Shibboleth should work on the server within a few days. Shib login will only be forced at /login as usual.

**Comment by orkit** [comment]
Shibboleth is now implemented on ResultPress. Users with the following entitlement can login:
urn:mace:swami.se:gmai:dsv-user:dsv-staff
This can be changed in the resultpress.ini file (/systemconfig/resultpress.ini).

**Comment by orkit** [comment]
For development purposes, you can: 
1) either comment row 23 and 42 in the routes file (web.php). This will disable the authentication check.
2) or you can use an emulated Shibboleth enviroment with Shibalike (via mrclay/shibalike). Set the EMULATE_IDP parameter in .env -> true. You can now login/logout with the routes /shinbboleth-login and /shibboleth-logout
