### ISSUE TITLE
Email reminders for activities

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#20]
There is a need to be able to configure email reminders to be sent when an activity is nearing its end date and is not yet marked as done. 

The exact contents of the reminder probably don't need configurability, just a simple email saying "There is less than a week left on [activity], please review your project and update as necessary." or something along those lines.

Whether reminders should be sent and at what date should be configurable per activity.

**Comment by orkit** [comment]
Email reminders are now implemented. A reminder email is sent out to the project owner when the activity is nearing its end date by the days defined in the activity settings, default set to 7 days. There is also the possiblility to switch reminders off.
The Task schedueler is set up to execute this check every day at midninght and we now need to add a Cron entry to your server to execute the task scheduelar every day.

Something like this?

* * * * * cd /var/www/resultpress && php artisan schedule:run >> /dev/null 2>&1

**Comment by orkit** [comment]
Changed scheduler to run a check everyday at 09.00.
