### ISSUE TITLE
Sane defaults on all input fields

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#21]
All input fields should assume sane defaults as far as possible (the "placeholder=" attribute on input tags is great for this):

* Number fields that pre-exist should assume 0 if no input is given (the total project budget field is a good example).
* User-created number fields should require input (an ouput on the project creation page is a good example)
* Text fields should be allowed to be blank, but a confirmation dialog should be shown if all text fields on the page are blank on submission.

**Comment by booski** [comment]
Budget fields that default to 0 still expect the user to provide a value.

**Comment by pavelsokolov** [comment]
Fixed now, default value for budget/outputs is 0.
