### ISSUE TITLE
Configurable access controls on projects

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#24]
Projects need access controls. There need to be at least three levels of general access:
 - Administrator: can do anything on any project
 - Program administrator: can do anything on any project linked to that program (once program areas get implemented)
 - Spider: can read anything and full write access to specified projects
 - Partner: read access to specified projects and update access to (possibly different) specified projects

The creator of a project should automatically be its 'owner', with the ability to assign further rights on that project to other users.
Administrators should always have owner-equivalent rights on all projects but not be listed as owners (unless they really do own some specific project). It should be possible to add further owners to a project.

Partner read views for projects will need to be separate from spider views, since some information is not to be exposed to project partners. The exact information to show/hide is unspecified at the moment and may differ between projects and/or project partners, so having the ability to specify certain 'classes' of information to expose to a specific project partner would be good. Something like a number of checkboxes when assigning access that grant access to specific parts of the project data would probably be a step in the right direction. The exact 'classes' are subject to change based on discussions with spider, but here are some initial ideas:
 - access to budget on specified/all activities
 - access to updates on specified/all activities
 - access to specified/all outputs

**Comment by booski** [comment]
It should be possible to clone access rights from one user to another, in order to support personnel changes. This goes for both spiders and partners.

**Comment by orkit** [comment]
The ACL is organized into roles and states. When logging in, a spider is assigned the role of ‘Spider’ and a partner the role of ‘Partner’. In addition, they are assigned various permissions, project-list, project-read,project- update, project-edit and project-create.
When a project is created, the specific permissions for that project are created, project-ID-list, project-ID-update, project-ID-create, project-ID-edit and project-ID-delete, which are assigned to the owner. If the project owner invites a partner, the partner is assigned the update-permission, project-ID-update for the individual project. Administrators have full permissions everywhere.
The roles and permissions are used to control what is exposed and shown to whom in different views etc.

**Comment by orkit** [comment]
The seeder has been improved and correct rights for Program administrator are now correctly loaded. The assign form has been restructured and Partners can now be assigned to a project by the owner or administrator.
