### ISSUE TITLE
Configurable project lists for spider users

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#25]
Spider users need to be able to narrow down the number of projects they see when logging in, while being able to find any project they have access to if they need to. This is of partially dependent on how program areas get implemented.

Upon login the user should be presented with a personal start page. It should consist of threee major parts:
 - Owned projects: all projects the user is an owner of
 - Program area projects: the user should be able to configure program areas of interest, whose projects all get listed (collated by program area)
 - All (other?) projects: a list of all projects the user has any access to at all. This should probably be initially collapsed for enhanced readability of the page once many projects exist on the platform.

**Comment by orkit** [comment]
Upon login the user is presented with a personal start page, MyProjects.  Upon the first login, the user is routed to a settings page where the user can set which projects they want to follow on MyProjects.

There is also a possibility of uploading an avatar for the user. (For use later in the ui).

I have been experimenting with a css-wrapper for enchaning the bootstrap table, which can be removed.
