### ISSUE TITLE
Establishing project and activity states

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#27]
The exact states possible for a project need to be established.

A starting point:
 - Pending (white): The project exists but its start date has not yet passed (I don't like this name but it's the best I can come up with atm)
 - In progress (yellow): The project has started and is not currently behind on anything
 - Delayed (red): Some activity has passed its expected end date without being marked as done
 - Pending review (blue): One or more updates have yet to be reviewed by spider
 - Finished (green): The end date has passed and all activities are marked as done
 - Archived (gray): The project has been marked as completely done and is not expected to need regular interaction any more

The archived state should be settable by a spider user at the project level. Other states are calculated.
Bonus points if delayed and pending review states somehow indicate which activities/updates they pertain to (tooltip? links?).

Activity states should be able to be largely similar:
 - Pending (white): Start date not yet passed and no updates exist
 - In progress (yellow): Start date has passed or an update exists
 - Delayed (red): The end date has passed but the activity is not marked as done
 - Pending review (blue): An update has been posted but not yet reviewed
 - Finished (green): Activity is marked as done

Marking an activity as done could be part of an update, or marking an activity as done may be done during spider update review, that needs clarification. Other states are calculated.

All these things are suggestions and should be discussed, please comment if you have ideas/opinions. Since the state is essentially metadata there should be no harm in changing these things after the platform is in use, so it does not have to be finished for the initial milestone.

An overarching decision of whether states should be explicit (set by a user) or implicit (calculated) may be necessary before initial release though. I'm leaning towards implicit as described above.

**Comment by booski** [comment]
Spider wants to mark activities as done as part of update review. That means that state configuration can be completely removed from the "write an update" page and a checkbox added to the "review update" page that allows the reviewer to mark the activity as done.

**Comment by PRindby** [comment]
@booski How about planned instead of pending for projects that have not started yet? (If I read your dislike correctly, if not - clarify)

**Comment by PRindby** [comment]
Another thing that I am not sure how it fits. Projects are sometimes redesigned because things change. 
Let's say the initial plan is to train radiologists to look for cervical cancer, but it turns out that they are not in need of training and it makes more sense to screen more women so project shifts focus to maybe train nurses but also make a campaing to get women to the clinics (so a completely different activity is added). Will these things fit into the states suggested or do we need to add more (cancelled, redesigned, added - especially for activities but perhaps also for projects to know which ones made adaptions.

**Comment by booski** [comment]
UI implementaion:

All state handling should be collected on the update writing page.

Project state changes should be collected under a new heading on the same heading-level as covered activities and affected outputs. Activity state changes should be part of the activity box.

The button to propose a state change should in both cases be labelled "Propose state change", and once clicked it should show a drop-down with the possible states to be set, ordered by their probability of being the "right" choice, so "completed" should be on top, followed by "on hold" and "cancelled".

Once a state to propose has been chosen, the button should change to indicate the selected state, and provide an option to reset the choice by clicking an X or similar to the right side of the button.

**Comment by PRindby** [comment]
**Project stages, suggestion after today's meeting**
We work on ux and colours and get back to that in a separate comment

•	Planned: The project exists but its start date has not yet passed 
•	In progress: The project has started and is not currently behind on anything
•	Delayed 1: Some minor activity has passed its expected end date without being marked as done (or other closing mark)
•	Delayed 2 : A major activity has passed its expected end date without being marked as done (or other closing mark) - OR many activites has passed its expected end date without being marked as done (or other closing mark)
•	Pending review: One or more updates have yet to be reviewed by spider
•	Completed: The project end date has passed and all activities are marked as done
•	Archived: The project has been marked as completely done and is not expected to need regular interaction any more
•	On hold: The project is frozen pending updates/investigations or similar. All reminders to partners are stopped. (motivation needed)
•	Terminated: The project is closed before its end date. Obligatory text box to state the reason for termination. This can only be done by a SPIDER user. 

As you can see I put 2 delayed to reflect the thing we talked about prioritising activities and up the alert for important activities being delayed. If those are two stages or different alert levels of the same I didn't grasp during the meeting.

**Comment by booski** [comment]
Two thoughts:

 - "Many" in delayed 2 needs further definition, or maybe the state should simply reflect the number of activities that are indeed delayed and hence not need to trigger "delayed 2" for numerous minor activities being behind. I'm thinking something along the lines of

State: Delayed 1 (3 activities delayed)

 - There might be a point in treating archived as a separate thing from the project states. I'm thinking that the archival state is more a matter of presentation in the UI than something pertaining to the project itself. For example a project might have been completed successfully or canceled halfway, and both can be archived after a while. Keeping the actual state of the project around (completed/canceled) when the project is archived seems to make sense.

**Comment by PRindby** [comment]
**Activity stages, suggestion after today's meeting**
•	Planned: Start date not yet passed and no updates exist
•	In progress: Start date has passed or an update exists
•	Delayed: The end date has passed but the activity is not marked as done
•	Pending review: An update has been posted but not yet reviewed’
•	Cancelled: The activity has been cancelled (reason needed to cancel)
•	Completed Activity is marked as done

**Comment by booski** [comment]
Re UI:

Since an update could conceivably just change the project state and nothing else, it should be possible to submit an update that doesn't cover an activity *if* that update proposes a state change for the project. 
In cases where a project state change is proposed in an update, the summary field should be treated as mandatory.

**Comment by PRindby** [comment]
> Two thoughts:
> 
> * "Many" in delayed 2 needs further definition, or maybe the state should simply reflect the number of activities that are indeed delayed and hence not need to trigger "delayed 2" for numerous minor activities being behind. I'm thinking something along the lines of
>   State: Delayed 1 (3 activities delayed)

Yes, that could make sense. And any delay to a major activity triggers the higher delay status. 
Would naming them _Delayed - minor_ and _Delayed - major_ work?

> * There might be a point in treating archived as a separate thing from the project states. I'm thinking that the archival state is more a matter of presentation in the UI than something pertaining to the project itself. For example a project might have been completed successfully or canceled halfway, and both can be archived after a while. Keeping the actual state of the project around (completed/canceled) when the project is archived seems to make sense.

Yes, I like that. Then the archive still provides information about how it went at a glance.

**Comment by pavelsokolov** [comment]
> • Completed: The project end date has passed and all activities are marked as done
> • Archived: The project has been marked as completely done and is not expected to need regular interaction any more
> • On hold: The project is frozen pending updates/investigations or similar. All reminders to partners are stopped. (motivation needed)
> • Terminated: The project is closed before its end date. Obligatory text box to state the reason for termination. This can only be done by a SPIDER user.

Completed sounds like something based on the conditions, so it is not set manually.

So we only have 3 custom states that should be added to 'project update' view: archived, on hold, terminated (which is removed if the end date has passed). 

Please verify.

**Comment by PRindby** [comment]
> > • Completed: The project end date has passed and all activities are marked as done
> > • Archived: The project has been marked as completely done and is not expected to need regular interaction any more
> > • On hold: The project is frozen pending updates/investigations or similar. All reminders to partners are stopped. (motivation needed)
> > • Terminated: The project is closed before its end date. Obligatory text box to state the reason for termination. This can only be done by a SPIDER user.
> 
> Completed sounds like something based on the conditions, so it is not set manually.
> 
> So we only have 3 custom states that should be added to 'project update' view: archived, on hold, terminated (which is removed if the end date has passed).
> 
> Please verify.

Yes, that must be correct. those are the only three that needs manual input.

**Comment by pavelsokolov** [comment]
This should be done now. Please play around and check :)

**Comment by PRindby** [comment]
Sure! Meeting David tomorrow so will set up a plan for some ways to check it :)
