### ISSUE TITLE
Updates that cover a date range

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#38]
Currently the date field on an activity covered by an update takes only a single date. It would be useful to be able to indicate that an update covers a time range, either by allowing "<date> - <date>" in a single field or by splitting to a start date and end date field.

I prefer the single field approach from a UI perspective, as long as the possibility to set a range is made obvious in some way.

**Comment by PRindby** [comment]
Yes, updates should cover a date range. 

``I prefer the single field approach from a UI perspective, as long as the possibility to set a range is made obvious in some way.``
Will it be apparent to the user that a date range is expected with a single field?

**Comment by pavelsokolov** [comment]
fixed in 3e28076
