### ISSUE TITLE
Integrated help functions

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#41]
The system needs explanatory texts in many places. Exactly how to implement this is open. Some possibilities:

 - Little help icons placed on page, popping up some information relevant to adjacent fields etc
 - A toggleable "help mode" that adds explanatory text on all fields etc. Think something like an interactive tutorial.
 - Tooltips on input fields that expand on the expected data beyond the label text

**Comment by orkit** [comment]
On all new additions and updates I have started to add small icons that trigger explanatory information / help text in the form of modals or tooltips.

**Comment by PRindby** [comment]
It is an option that works for me. 
Maybe we see if David has input after his testing actual projects.

**Comment by pavelsokolov** [comment]
Alternatively we can use Tooltips.
<img width="597" alt="Screenshot 2021-02-10 at 15 40 20" src="https://user-images.githubusercontent.com/3234777/107511253-4ae9fa80-6bb6-11eb-9d8c-2c2c5fef6802.png">

**Comment by pavelsokolov** [comment]
Tooltips added in most places, it's then up to Spider to define texts and discover new areas to get help texts. Closing this for now.
