### ISSUE TITLE
No mail is sent to the Partner when the Project manager Rejected or Accepted an Update. 

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#53]

**Comment by orkit** [comment]
![Screenshot 2021-04-06 at 10 49 47](https://user-images.githubusercontent.com/22212903/113685080-2bf37a80-96c6-11eb-879a-fa108845733b.png)
![Screenshot 2021-04-06 at 10 50 05](https://user-images.githubusercontent.com/22212903/113685095-2eee6b00-96c6-11eb-85a6-91bbee29a553.png)
