### ISSUE TITLE
An 404 error is showed when I hit the Edit Button when an updates is rejected and marked as Draft.  

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#56]
David can elaborate or add screenshots.

**Comment by pavelsokolov** [comment]
This was resolved. It's 400 rather than 404 error, because he tried to edit an update created by his test user. Only update's author can edit it. But you're free to revise the setup.

**Comment by PRindby** [comment]
Well, no I think this problem is better solved by using the correct user.
