### ISSUE TITLE
Character limit for outputs - need warning!

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#61]
There is a character limit for the outputs (good!), but no warning when this is exceeded. 
So when trying to save all is lost in an error message.

Could the limit be shown (max xx characters) - and a warning for when it is exceeded.

Also - what is the current limit? Apparently below 250 characters.

**Comment by booski** [comment]
Maybe it would be possible to have a live counter in or near the relevant field? 
"34/250 characters used" or similar.

**Comment by pavelsokolov** [comment]
Ok, then the outputs layout has to be redesigned as well. It was supposed that it'd be some short name + numeric target, rather than long descriptive string.

**Comment by PRindby** [comment]
I would prefer it to stay that way also. That is something SPIDER need to clarify in terms of project design going forward. 
It does not make sense for an output to be a short story. 
But a warning when you hit the cap will help with the ones we have to deal with now..
