### ISSUE TITLE
Petra can't update a project David has entered

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#64]
Not sure if this is the way it is supposed to be or something with my profile.

**Comment by orkit** [comment]
if you need to update a project, you need to be a manager on the project. Only mangers can update a project. In the admin view there is "Manage projects".

![Screenshot 2021-02-25 at 14 45 02](https://user-images.githubusercontent.com/22212903/109162796-ea8fb700-7778-11eb-863a-68a7da057838.png)

Here you get a listing of all projects and you can choose to edit permissions with the edit button.

![Screenshot 2021-02-25 at 14 52 55](https://user-images.githubusercontent.com/22212903/109163024-288cdb00-7779-11eb-8325-377417967043.png)

You can then change your role to manager on the project you want to edit.

![Screenshot 2021-02-25 at 14 53 57](https://user-images.githubusercontent.com/22212903/109163325-81f50a00-7779-11eb-993f-9dcf571f185d.png)

**Comment by orkit** [comment]
Editing of project managers and partners can now be performed directly in the editing mode of a project.
