### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#69]
Resultspress needs a full search function to find projects based on a diverse set of criteria that goes beyond filtering.

These could include: country, thematic area, or any freetext options such as refugees or disabilities.

**Comment by pavelsokolov** [comment]
Should we consider this as done? I think the current requirements have been met, projects are searched by either title or description (with an autocomplete suggestions), and search results view enables to filter by Manager, Partner, Area

**Comment by PRindby** [comment]
I want the search bar on the page "projects" also  (right now it is on "my projects" only) - then I am happy. 
The autocomplete I like very much.

**Comment by pavelsokolov** [comment]
Added now.
