### ISSUE TITLE
Project updates should be more flexible

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#9]
Trying to create an update that doesn't cover any outputs currently results in an error. This should be fixed. It should be discussed with spider whether an update must cover an activity at all.

It's probably not meaningful to allow updates that cover only outputs.

**Comment by pavelsokolov** [comment]
The error caused by empty ouputs is now gone, so closing the issue. It's possible to create an update that doesn't include either activities or outputs, for flexibility reasons.
